version: '3'
services:
  node_dev:
    image: node:10.16.0-alpine
    container_name: node-docker
    user: node
    working_dir: /home/app
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
